import '@/styles/globals.css'
import Head from "next/head";
import Script from "next/script";
import Layout from "../comps/Layout";
import Link from 'next/link';


export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Sigma Machines</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <Link href="/dist/output.css" rel="stylesheet" />
        {/* <link rel="icon" href="/logo.png" /> */}
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  )
}
